title: seahatvn
logo: /assets/img/logo.png
description: Server Hack Team
show_downloads: true
google_analytics:
remote_theme: r3kapig
exclude: ['_site', 'node_modules', 'script', 'LICENSE', 'README.md']
