title: seahatvn
logo: /assets/img/logo.png
description: Server Hack Team
show_downloads: true
google_analytics:
# theme: r3kapig # use in local, don't commit this file
remote_theme: r3kapig/r3kapig.github.io # for remote
exclude: ['_site', 'node_modules', 'script', 'LICENSE', 'README.md']
